import { Metadata } from "next";

const keywords = [
    // Core Anonymous Chat Concepts
    'anonymous chat',
    'real-time messaging',
    'private chat rooms',
    'fearless conversations',
    'temporary chat',
    'dark web style chat',
    'self-destructing messages',
    'anonymous discussions',
    'chat without fear',
    'secure chat',
    'random chat rooms',
    'private messaging',
    'untraceable chat',
    'honest conversations',
    'temporary server chat',
    'dark web chat',
    
    // Privacy & Security Features
    'no account chat',
    'encrypted messaging',
    'no-log chat',
    'identity protection chat',
    'VPN compatible chat',
    'Tor-friendly messaging',
    'zero-knowledge chat',
    'metadata-free conversations',
    'encrypted chat rooms',
    'secure communication',
    'anonymous communication',
    'data-free messaging',
    'privacy chat app',
    'hidden identity chat',
    'no-signup chat',
    'no-registration messaging',
    'anti-tracking chat',
    'digital privacy chat',
    'incognito messaging',
    'anonymous messaging platform',
    'private conversations',
    'vanishing messages',
    'disappearing texts',
    'privacy-focused chat',
    'end-to-end encrypted chat',
    'no-trace messaging',
    'no-history chat',
    'burner chat rooms',
    'disposable chat',
    'confidential messaging',
    'secretive conversations',
    
    // User Experience Keywords
    'ephemeral chat',
    'temporary discussion rooms',
    'speak freely online',
    'judgment-free conversations',
    'honest dialogue platform',
    'spontaneous discussions',
    'no-strings-attached chat',
    'chat and disappear',
    'ghost chat room',
    'anonymous social platform',
    'pressure-free discussions',
    'free speech platform',
    'open dialogue rooms',
    'anonymous opinion sharing',
    'candid conversation app',
    'unfiltered discussions',
    'anonymous social network',
    'express yourself freely',
    'uninhibited conversations',
    'temporary connection app',
    'momentary chat rooms',
    'no-consequence discussions',
    'anonymous feedback platform',
    'real conversations app',
    'genuine dialogue rooms',
    'mask-on conversations',
    'digital mask chat',
    'social disguise platform',
    
    // Technical & Feature-Based Keywords
    'decentralized chat',
    'peer-to-peer messaging',
    'blockchain chat',
    'serverless messaging',
    'distributed chat network',
    'cryptographic chat',
    'self-destructing chat rooms',
    'timed message deletion',
    'message burn after reading',
    'auto-delete conversations',
    'message expiration chat',
    'session-based chat',
    'tor-routed messaging',
    'onion routing chat',
    'off-the-grid messaging',
    'distributed chat protocol',
    'anti-surveillance messaging',
    'censorship-resistant chat',
    'fingerprint-free chat',
    'anti-censorship platform',
    'untraceable messages',
    'secure communication channel',
    'leak-proof messaging',
    'signal-protocol chat',
    'zero-knowledge proof messaging',
    
    // Use Cases & Scenarios
    'whistleblower chat platform',
    'anonymous reporting tool',
    'secure source communication',
    'journalist-source chat',
    'sensitive discussions app',
    'confidential advice platform',
    'anonymous therapy chat',
    'secure confessional app',
    'anonymous venting platform',
    'secure debate platform',
    'anonymous opinion polling',
    'secret voting discussions',
    'anonymous brainstorming rooms',
    'confidential meeting space',
    'secret team communications',
    'anonymous Q&A platform',
    'safe space for discussion',
    'controversial topic chat',
    'taboo subject discussions',
    'stigma-free conversation',
    'judgment-free dialogue',
    'opinion-sharing without consequences',
    'anonymous confession platform',
    'safe identity discussions',
    'personal secret sharing',
    'anonymous support groups',
    'hidden identity forums',
    
    // Emotional & Psychological Keywords
    'liberation through anonymity',
    'freedom to speak freely',
    'uninhibited expression platform',
    'authentic self platform',
    'true thoughts messenger',
    'honest feedback platform',
    'genuine reaction sharing',
    'emotional unburdening app',
    'psychological safety chat',
    'no-judgment zone',
    'digital confession booth',
    'emotional freedom platform',
    'truth-speaking app',
    'cathartic conversation app',
    'release through anonymity',
    'unburdened discussions',
    'anonymous emotional support',
    'free thought exchange',
    'unfiltered opinion platform',
    'authentic discussion rooms',
    'digital masquerade chat',
    'free from identity constraints',
    'personality-free discussions',
    
    // Comparison & Alternative Keywords
    'better than Reddit anonymous',
    'Discord alternative private',
    'safer than Telegram',
    'more anonymous than Signal',
    'WhatsApp alternative secure',
    'private alternative to Facebook Messenger',
    'Twitter DM alternative',
    'anonymous 4chan alternative',
    'secure Snapchat alternative',
    'Instagram DM replacement',
    'anonymous YouTube comments alternative',
    'safer than public forums',
    'anonymous version of Slack',
    'private Teams alternative',
    'secure Skype replacement',
    'more private than Zoom chat',
    'anonymous Google Meet alternative',
    'private chat revolution',
    'next-gen anonymous platform',
    
    // Industry & Niche-Specific Keywords
    'corporate leaks platform',
    'anonymous business discussions',
    'confidential corporate chat',
    'healthcare privacy chat',
    'HIPAA-friendly messaging',
    'lawyer-client secure chat',
    'financial discussion privacy',
    'anonymous investing discussions',
    'secure political conversations',
    'anonymous activism platform',
    'secure protest coordination',
    'anonymous journalism platform',
    'secure source protection',
    'medical privacy chat',
    'anonymous patient support',
    'workplace whistleblowing platform',
    'anonymous HR reporting',
    'secure academic discussions',
    'anonymous research collaboration',
    'secure invention discussion',
    'anonymous creative collaboration',
    'secure government whistleblowing',
    'anonymous policy discussions',
    
    // Action & Intent Keywords
    'speak without consequences',
    'chat without tracking',
    'message without identity',
    'discuss without fear',
    'communicate securely',
    'share opinions anonymously',
    'connect without traces',
    'talk without identification',
    'express without judgment',
    'chat without data collection',
    'message without monitoring',
    'discuss without surveillance',
    'communicate without records',
    'share without attribution',
    'connect without cookies',
    'talk without logging',
    'express without accounts',
    'chat without registration',
    'message without profiles',
    'discuss without history',
    'communicate without footprints',
    'share without identifiers',
    'connect without cookies',
    'talk without tracking pixels',
    'express without facial recognition',
    
    // Technical Security Keywords
    'zero-knowledge encryption chat',
    'military-grade encryption messaging',
    'AES-256 encrypted chat',
    'quantum-resistant messaging',
    'forward secrecy chat',
    'double ratchet algorithm messaging',
    'perfect forward secrecy',
    'cryptographic deniability',
    'anonymous relay chat',
    'multi-layered encryption',
    'ephemeral key exchange',
    'off-the-record messaging',
    'secure multi-party computation chat',
    'homomorphic encryption messaging',
    'trustless communication protocol',
    'zero-trust architecture chat',
    'encrypted P2P messaging',
    'security-first communication',
    'leak-proof architecture',
    'anti-forensic messaging',
    'trace-resistant protocol',
    'deniable authentication chat',
    'attribution-resistant messaging',
    
    // Emerging Privacy Trends
    'Web3 anonymous chat',
    'decentralized identity messaging',
    'zero-knowledge proof chat',
    'blockchain-secured messaging',
    'NFT-based anonymous identity',
    'DeFi-style private communication',
    'metaverse anonymous interactions',
    'crypto-secured chat rooms',
    'DAC communication platform',
    'tokenized anonymous access',
    'post-quantum encryption chat',
    'anti-AI tracking messaging',
    'facial recognition resistant',
    'voice-anonymizing chat',
    'style-masking communication',
    'AI-resistant anonymity',
    'biometric-free messaging',
    'identity-obfuscation platform',
    'smart contract secured messages',
    'autonomous privacy protocol',
    'self-sovereign identity chat',
    'privacy-preserving machine learning chat',
    'federated anonymous learning',
    
    // Location & Political Keywords
    'censorship-free in China',
    'anonymous chat in restrictive countries',
    'bypass internet censorship',
    'freedom of speech platform',
    'global privacy chat',
    'cross-border anonymous communication',
    'region-locked content discussion',
    'politically sensitive discussions',
    'high surveillance area chat',
    'authoritarian regime safe chat',
    'firewall-bypassing communication',
    'resistance communication platform',
    'diplomatic back-channel alternative',
    'secure border-crossing communication',
    'exile community platform',
    'refugee secure communication',
    'diaspora private network',
    'dissident protection chat',
    'human rights defender platform',
    'cross-regime secure chat',
    'underground network communication',
    'free speech zone online',
    'internet freedom tool',
    
    // Longtail & Specific Feature Keywords
    'disappearing message timer',
    'customizable privacy settings',
    'anonymous group chat creation',
    'secure file sharing anonymously',
    'encrypted voice messages',
    'private image sharing',
    'secret conversation starter',
    'anonymous video chat',
    'secure audio messaging',
    'zero-trace file transfer',
    'temporary chat room generator',
    'password-protected chat rooms',
    'invite-only secret rooms',
    'burn-after-reading attachment',
    'security PIN protected chat',
    'anti-screenshot protection',
    'paste-proof messaging',
    'clipboard-protected chat',
    'multi-device secure sync',
    'offline encrypted messaging',
    'air-gapped communication',
    'tamper-evident messages',
    'verification without identification',
    'read receipt without tracking',
    'typing indicator without logging',
    'presence indicator without monitoring'
]

export const homeMetadata: Metadata = {
    title: 'Secret Room — Speak from the Shadows',
    description: "Wander into the shadows of the web. Secret Room is an anonymous chat realm where voices echo briefly—free, raw, and untraceable.",
    keywords: keywords,
    authors: [{ name: "Fabiconcept", url: "https://fabiconcept.online" }],
    creator: 'Fabiconcept',
    openGraph: {
        title: 'Secret Room — Speak from the Shadows',
        description: "Wander into the shadows of the web. Secret Room is an anonymous chat realm where voices echo briefly—free, raw, and untraceable.",
        url: 'https://secret-room-orpin.vercel.app',
        locale: 'en_US',
        images: [
            {
                url: 'https://secret-room.sirv.com/snapshots/thumbnail-main.png',
                width: 1200,
                height: 630,
                alt: 'Secret Room Chat Interface',
            },
        ],
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Secret Room — Speak from the Shadows',
        description: 'Unmask your thoughts. Speak freely, vanish without a trace. Secret Room awaits.',
        images: ['https://secret-room.sirv.com/snapshots/thumbnail-main.png'],
    },
    icons: {
        icon: 'https://secret-room.sirv.com/favicon/android-chrome-192x192.png',
        shortcut: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        apple: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        other: {
            rel: 'https://secret-room.sirv.com/favicon/favicon.ico',
            url: 'https://secret-room.sirv.com/favicon/favicon.ico',
        },
    },
    robots: {
        index: true,
        follow: true,
        nocache: true,
        googleBot: {
            index: true,
            follow: true,
            noimageindex: false,
            'max-video-preview': -1,
            'max-image-preview': 'large',
            'max-snippet': -1,
        },
    },
};

export const GlobalInviteMetadata: Metadata = {
    title: "Secret Room — Your Portal Awaits",
    description: "Slip into the unknown. Meet strangers in a fleeting veil of darkness. No history. No judgment. Just voices in the void.",
    keywords: keywords,
    authors: [{ name: "Fabiconcept", url: "https://fabiconcept.online" }],
    creator: 'Fabiconcept',
    openGraph: {
        title: "Secret Room — Your Portal Awaits",
        description: "Slip into the unknown. Meet strangers in a fleeting veil of darkness. No history. No judgment. Just voices in the void.",
        siteName: "Secret Room",
        images: [
            {
                url: "https://secret-room.sirv.com/snapshots/thumbnail-main.png",
                width: 1200,
                height: 630,
                alt: "Secret Room - Global Invite"
            }
        ],
        type: "website"
    },
    icons: {
        icon: 'https://secret-room.sirv.com/favicon/android-chrome-192x192.png',
        shortcut: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        apple: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        other: {
            rel: 'https://secret-room.sirv.com/favicon/favicon.ico',
            url: 'https://secret-room.sirv.com/favicon/favicon.ico',
        },
    },
    twitter: {
        card: "summary_large_image",
        title: "Secret Room — Your Portal Awaits",
        description: "Speak freely, disappear completely. One link. One moment. No return.",
        images: ["https://secret-room.sirv.com/snapshots/thumbnail-main.png"]
    }
};

export const ServerMetadata: Metadata = {
    title: "Secret Room — Live Shadows",
    description: "You’ve entered the dark. A real-time, anonymous space where your words fade as fast as they arrive. Time is short. Say what matters.",
    keywords: keywords,
    authors: [{ name: "Fabiconcept", url: "https://fabiconcept.online" }],
    creator: 'Fabiconcept',
    icons: {
        icon: 'https://secret-room.sirv.com/favicon/android-chrome-192x192.png',
        shortcut: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        apple: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        other: {
            rel: 'https://secret-room.sirv.com/favicon/favicon.ico',
            url: 'https://secret-room.sirv.com/favicon/favicon.ico',
        },
    },
    openGraph: {
        title: "Secret Room — Live Shadows",
        description: "Connected in whispers. Anonymous by default. Temporary by design.",
        siteName: "Secret Room",
        images: [
            {
                url: "https://secret-room.sirv.com/snapshots/thumbnail-main.png",
                width: 1200,
                height: 630,
                alt: "Secret Room Server"
            }
        ],
        type: "website"
    },
    twitter: {
        card: "summary_large_image",
        title: "Secret Room — Live Shadows",
        description: "Your words flicker in the dark. Speak now — then vanish.",
        images: ["https://secret-room.sirv.com/snapshots/thumbnail-main.png"]
    }
};

export const PrivateInviteMetadata: Metadata = {
    title: "Secret Room — Private Passage",
    description: "You've been summoned. Step through this one-time gate into a private, ephemeral chat. No names. No footprints. Just presence.",
    keywords: keywords,
    authors: [{ name: "Fabiconcept", url: "https://fabiconcept.online" }],
    creator: 'Fabiconcept',
    icons: {
        icon: 'https://secret-room.sirv.com/favicon/android-chrome-192x192.png',
        shortcut: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        apple: 'https://secret-room.sirv.com/favicon/android-chrome-512x512.png',
        other: {
            rel: 'https://secret-room.sirv.com/favicon/favicon.ico',
            url: 'https://secret-room.sirv.com/favicon/favicon.ico',
        },
    },
    openGraph: {
        title: "Secret Room — Private Passage",
        description: "A one-time link. A quiet voice in the night. No tracking. No replay. Just this moment.",
        siteName: "Secret Room",
        images: [
            {
                url: "https://secret-room.sirv.com/snapshots/thumbnail-main.png",
                width: 1200,
                height: 630,
                alt: "Secret Room - Private Chat"
            }
        ],
        type: "website"
    },
    twitter: {
        card: "summary_large_image",
        title: "Secret Room — Private Passage",
        description: "This invite fades soon. Speak what haunts you and disappear.",
        images: ["https://secret-room.sirv.com/snapshots/thumbnail-main.png"]
    }
};
  