import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { SocketProvider } from "@/app/components/contexts/SocketContext";
import HomeBackground from "./components/HomeBackground";
import SoundTrack from "./components/SoundTrack";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 5000,
          }}

        />
        <div className="bg absolute h-screen w-screen top-0 left-0"></div>
        <HomeBackground />
        {/* <SoundTrack /> */}
        <SocketProvider>
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
